In [ ]:
# %pip install openpyxl ( install if any error occur on excel file)

In [24]:
import pandas as pd

In [25]:
pd.__version__

'2.3.3'

In [26]:
df = pd.read_excel(r'D:\NIT\1. NIT_Batches\1. MORNING BATCH\N_Batch -- 7.30AM _ Dec26\2. July\21st, 22nd - Pandas\Country GDP Analysis- project\data.xlsx')

In [27]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [28]:
len(df)

195

In [29]:
df.shape

(195, 5)

In [30]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [31]:
len(df.columns)

5

In [32]:
df.isnull()

     CountryName  CountryCode  BirthRate  InternetUsers  IncomeGroup
0          False        False      False          False        False
1          False        False      False          False        False
2          False        False      False          False        False
3          False        False      False          False        False
4          False        False      False          False        False
..           ...          ...        ...            ...          ...
190        False        False      False          False        False
191        False        False      False          False        False
192        False        False      False          False        False
193        False        False      False          False        False
194        False        False      False          False        False

[195 rows x 5 columns]

In [33]:
df.isnull().sum()

CountryName      0
CountryCode      0
BirthRate        0
InternetUsers    0
IncomeGroup      0
dtype: int64

In [34]:
df.isna().sum()

CountryName      0
CountryCode      0
BirthRate        0
InternetUsers    0
IncomeGroup      0
dtype: int64

In [35]:
type(df)

pandas.core.frame.DataFrame

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CountryName    195 non-null    object
 1   CountryCode    195 non-null    object
 2   BirthRate      195 non-null    float64
 3   InternetUsers  195 non-null    float64
 4   IncomeGroup    195 non-null    object
dtypes: float64(2), object(3)
memory usage: 7.7+ KB

In [37]:
df.head() # print top 5 rows

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income

In [38]:
df.tail()

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [39]:
df.head(2)

   CountryName CountryCode  BirthRate  InternetUsers  IncomeGroup
0        Aruba         ABW     10.244           78.9  High income
1  Afghanistan         AFG     35.253            5.9   Low income

In [40]:
df.tail(3)

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [41]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [42]:
df[:]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [43]:
df[:10]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9000,High income
1,Afghanistan,AFG,35.253,5.9000,Low income
2,Angola,AGO,45.985,19.1000,Upper middle income
3,Albania,ALB,12.877,57.2000,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0000,High income
5,Argentina,ARG,17.716,59.9000,High income
6,Armenia,ARM,13.308,41.9000,Lower middle income
7,Antigua and Barbuda,ATG,16.447,63.4000,High income
8,Australia,AUS,13.200,83.0000,High income
9,Austria,AUT,9.400,80.6188,High income

In [44]:
df[10:]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
10,Azerbaijan,AZE,18.300,58.7000,Upper middle income
11,Burundi,BDI,44.151,1.3000,Low income
12,Belgium,BEL,11.200,82.1702,High income
13,Benin,BEN,36.440,4.9000,Low income
14,Burkina Faso,BFA,40.551,9.1000,Low income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0000,Lower middle income
191,South Africa,ZAF,20.850,46.5000,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2000,Low income
193,Zambia,ZMB,40.471,15.4000,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5000,Low income

In [45]:
df[10:20]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
10,Azerbaijan,AZE,18.300,58.70000,Upper middle income
11,Burundi,BDI,44.151,1.30000,Low income
12,Belgium,BEL,11.200,82.17020,High income
13,Benin,BEN,36.440,4.90000,Low income
14,Burkina Faso,BFA,40.551,9.10000,Low income
15,Bangladesh,BGD,20.142,6.63000,Lower middle income
16,Bulgaria,BGR,9.200,53.06150,Upper middle income
17,Bahrain,BHR,15.040,90.00004,High income
18,"Bahamas, The",BHS,15.339,72.00000,High income
19,Bosnia and Herzegovina,BIH,9.062,57.79000,Upper middle income

In [46]:
df[::10]

     CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0          Aruba         ABW     10.244      78.900000          High income
10    Azerbaijan         AZE     18.300      58.700000  Upper middle income
20       Belarus         BLR     12.500      54.170000  Upper middle income
30        Canada         CAN     10.900      85.800000          High income
40    Costa Rica         CRI     15.022      45.960000  Upper middle income
50       Ecuador         ECU     21.070      40.353684  Upper middle income
60         Gabon         GAB     30.555       9.200000  Upper middle income
70     Greenland         GRL     14.500      65.800000          High income
80         India         IND     20.291      15.100000  Lower middle income
90    Kazakhstan         KAZ     22.730      54.000000  Upper middle income
100        Libya         LBY     21.425      16.500000  Upper middle income
110      Moldova         MDA     12.141      45.000000  Lower middle income
120   Mozambique         MOZ     39.705       5.400000           Low income
130  Netherlands         NLD     10.200      93.956400          High income
140       Poland         POL      9.600      62.849200          High income
150        Sudan         SDN     33.477      22.700000  Lower middle income
160     Suriname         SUR     18.455      37.400000  Upper middle income
170   Tajikistan         TJK     30.792      16.000000  Lower middle income
180      Uruguay         URY     14.374      57.690000          High income
190  Yemen, Rep.         YEM     32.947      20.000000  Lower middle income

In [48]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [50]:
df.dtypes

CountryName       object
CountryCode       object
BirthRate        float64
InternetUsers    float64
IncomeGroup       object
dtype: object

In [51]:
df.head(2)

   CountryName CountryCode  BirthRate  InternetUsers  IncomeGroup
0        Aruba         ABW     10.244           78.9  High income
1  Afghanistan         AFG     35.253            5.9   Low income

In [57]:
df['BirthRate']

0      10.244
1      35.253
2      45.985
3      12.877
4      11.044
        ...
190    32.947
191    20.850
192    42.394
193    40.471
194    35.715
Name: BirthRate, Length: 195, dtype: float64

In [56]:
df[['InternetUsers', 'CountryCode']]

     InternetUsers CountryCode
0             78.9         ABW
1              5.9         AFG
2             19.1         AGO
3             57.2         ALB
4             88.0         ARE
..             ...         ...
190           20.0         YEM
191           46.5         ZAF
192            2.2         COD
193           15.4         ZMB
194           18.5         ZWE

[195 rows x 2 columns]

In [59]:
df[['CountryName', 'CountryCode', 'BirthRate' ]]

              CountryName CountryCode  BirthRate
0                   Aruba         ABW     10.244
1             Afghanistan         AFG     35.253
2                  Angola         AGO     45.985
3                 Albania         ALB     12.877
4    United Arab Emirates         ARE     11.044
..                    ...         ...        ...
190           Yemen, Rep.         YEM     32.947
191          South Africa         ZAF     20.850
192      Congo, Dem. Rep.         COD     42.394
193                Zambia         ZMB     40.471
194              Zimbabwe         ZWE     35.715

[195 rows x 3 columns]

# split the dataset into numerical dataframes & categorical dataframe

In [60]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [61]:
df_num = df[['BirthRate', 'InternetUsers']] 
df_cat = df[[ 'CountryName', 'CountryCode', 'IncomeGroup']]

In [63]:
df_num.head(2)

   BirthRate  InternetUsers
0     10.244           78.9
1     35.253            5.9

In [64]:
df_cat.head(2)

   CountryName CountryCode  IncomeGroup
0        Aruba         ABW  High income
1  Afghanistan         AFG   Low income

In [67]:
print(df_num.columns) 
print(df_cat.columns)

Index(['BirthRate', 'InternetUsers'], dtype='object')
Index(['CountryName', 'CountryCode', 'IncomeGroup'], dtype='object')

In [68]:
df.describe()

        BirthRate  InternetUsers
count  195.000000     195.000000
mean    21.469928      42.076471
std     10.605467      29.030788
min      7.900000       0.900000
25%     12.120500      14.520000
50%     19.680000      41.000000
75%     29.759500      66.225000
max     49.661000      96.546800

In [69]:
df_num.describe()

        BirthRate  InternetUsers
count  195.000000     195.000000
mean    21.469928      42.076471
std     10.605467      29.030788
min      7.900000       0.900000
25%     12.120500      14.520000
50%     19.680000      41.000000
75%     29.759500      66.225000
max     49.661000      96.546800

In [70]:
df_cat

              CountryName CountryCode          IncomeGroup
0                   Aruba         ABW          High income
1             Afghanistan         AFG           Low income
2                  Angola         AGO  Upper middle income
3                 Albania         ALB  Upper middle income
4    United Arab Emirates         ARE          High income
..                    ...         ...                  ...
190           Yemen, Rep.         YEM  Lower middle income
191          South Africa         ZAF  Upper middle income
192      Congo, Dem. Rep.         COD           Low income
193                Zambia         ZMB  Lower middle income
194              Zimbabwe         ZWE           Low income

[195 rows x 3 columns]

In [71]:
df_cat.describe()

       CountryName CountryCode  IncomeGroup
count          195         195          195
unique         195         195            4
top          Aruba         ABW  High income
freq             1           1           67

In [72]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [74]:
df.columns = ['a', 'b', 'c', 'd', 'e']

In [75]:
df.head(2)

             a    b       c     d            e
0        Aruba  ABW  10.244  78.9  High income
1  Afghanistan  AFG  35.253   5.9   Low income

In [76]:
df.columns = ['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers', 'IncomeGroup']

In [77]:
df.head(1)

  CountryName CountryCode  BirthRate  InternetUsers  IncomeGroup
0       Aruba         ABW     10.244           78.9  High income

In [78]:
BirthRate * InternetUsers

NameError: name 'BirthRate' is not defined

In [79]:
df.BirthRate * df.InternetUsers

0      808.2516
1      207.9927
2      878.3135
3      736.5644
4      971.8720
         ...
190    658.9400
191    969.5250
192     93.2668
193    623.2534
194    660.7275
Length: 195, dtype: float64

In [80]:
df['myCalc'] = df.BirthRate * df.InternetUsers

In [81]:
df.head(2)

   CountryName CountryCode  BirthRate  InternetUsers  IncomeGroup    myCalc
0        Aruba         ABW     10.244           78.9  High income  808.2516
1  Afghanistan         AFG     35.253            5.9   Low income  207.9927

In [82]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup', 'myCalc'],
      dtype='object')

In [83]:
id(df)

2703844392464

In [84]:
df = df.drop('myCalc',axis = 1)

In [85]:
df.head(1)

  CountryName CountryCode  BirthRate  InternetUsers  IncomeGroup
0       Aruba         ABW     10.244           78.9  High income

# filter in dataframe

In [86]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [88]:
df['InternetUsers'] < 2

0      False
1      False
2      False
3      False
4      False
       ...
190    False
191    False
192    False
193    False
194    False
Name: InternetUsers, Length: 195, dtype: bool

In [89]:
df[df['InternetUsers'] < 2]

      CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
11        Burundi         BDI     44.151            1.3           Low income
52        Eritrea         ERI     34.800            0.9           Low income
55       Ethiopia         ETH     32.925            1.9           Low income
64         Guinea         GIN     37.337            1.6           Low income
117       Myanmar         MMR     18.119            1.6  Lower middle income
127         Niger         NER     49.661            1.7           Low income
154  Sierra Leone         SLE     36.729            1.7           Low income
156       Somalia         SOM     43.891            1.5           Low income
172   Timor-Leste         TLS     35.755            1.1  Lower middle income

In [90]:
len(df[df['InternetUsers'] < 2])

9

In [91]:
df[df['BirthRate'] > 40]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
2,Angola,AGO,45.985,19.1,Upper middle income
11,Burundi,BDI,44.151,1.3,Low income
14,Burkina Faso,BFA,40.551,9.1,Low income
65,"Gambia, The",GMB,42.525,14.0,Low income
115,Mali,MLI,44.138,3.5,Low income
127,Niger,NER,49.661,1.7,Low income
128,Nigeria,NGA,40.045,38.0,Lower middle income
156,Somalia,SOM,43.891,1.5,Low income
167,Chad,TCD,45.745,2.3,Low income
178,Uganda,UGA,43.474,16.2,Low income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income

In [92]:
len(df[df['BirthRate'] > 40])

12

In [94]:
df[(df.BirthRate > 40) & (df.InternetUsers < 3)]

          CountryName CountryCode  BirthRate  InternetUsers IncomeGroup
11            Burundi         BDI     44.151            1.3  Low income
127             Niger         NER     49.661            1.7  Low income
156           Somalia         SOM     43.891            1.5  Low income
167              Chad         TCD     45.745            2.3  Low income
192  Congo, Dem. Rep.         COD     42.394            2.2  Low income

In [95]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [98]:
df[df.IncomeGroup == 'Lower middle income']

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
6,Armenia,ARM,13.308,41.9000,Lower middle income
15,Bangladesh,BGD,20.142,6.6300,Lower middle income
23,Bolivia,BOL,24.236,36.9400,Lower middle income
27,Bhutan,BTN,18.134,29.9000,Lower middle income
34,Cote d'Ivoire,CIV,37.320,8.4000,Lower middle income
35,Cameroon,CMR,37.236,6.4000,Lower middle income
36,"Congo, Rep.",COG,37.011,6.6000,Lower middle income
39,Cabo Verde,CPV,21.625,37.5000,Lower middle income
46,Djibouti,DJI,25.486,9.5000,Lower middle income
51,"Egypt, Arab Rep.",EGY,28.032,29.4000,Lower middle income
59,"Micronesia, Fed. Sts.",FSM,23.511,27.8000,Lower middle income
62,Georgia,GEO,13.332,43.3000,Lower middle income
63,Ghana,GHA,33.131,12.3000,Lower middle income
71,Guatemala,GTM,27.465,19.7000,Lower middle income
73,Guyana,GUY,18.885,35.0000,Lower middle income
75,Honduras,HND,21.593,17.8000,Lower middle income
79,Indonesia,IDN,20.297,14.9400,Lower middle income
80,India,IND,20.291,15.1000,Lower middle income
91,Kenya,KEN,35.194,39.0000,Lower middle income
92,Kyrgyz Republic,KGZ,27.200,23.0000,Lower middle income
94,Kiribati,KIR,29.044,11.5000,Lower middle income
97,Lao PDR,LAO,27.051,12.5000,Lower middle income
103,Sri Lanka,LKA,17.863,21.9000,Lower middle income
104,Lesotho,LSO,28.738,5.0000,Lower middle income
109,Morocco,MAR,21.023,56.0000,Lower middle income
110,Moldova,MDA,12.141,45.0000,Lower middle income
117,Myanmar,MMR,18.119,1.6000,Lower middle income
121,Mauritania,MRT,33.801,6.2000,Lower middle income
128,Nigeria,NGA,40.045,38.0000,Lower middle income
129,Nicaragua,NIC,20.788,15.5000,Lower middle income
135,Pakistan,PAK,29.582,10.9000,Lower middle income
138,Philippines,PHL,23.790,37.0000,Lower middle income
139,Papua New Guinea,PNG,28.899,6.5000,Lower middle income
150,Sudan,SDN,33.477,22.7000,Lower middle income
151,Senegal,SEN,38.533,13.1000,Lower middle income
153,Solomon Islands,SLB,30.578,8.0000,Lower middle income
155,El Salvador,SLV,17.476,23.1093,Lower middle income
159,Sao Tome and Principe,STP,34.537,23.0000,Lower middle income
164,Swaziland,SWZ,30.093,24.7000,Lower middle income
166,Syrian Arab Republic,SYR,24.043,26.2000,Lower middle income
170,Tajikistan,TJK,30.792,16.0000,Lower middle income
172,Timor-Leste,TLS,35.755,1.1000,Lower middle income
179,Ukraine,UKR,11.100,41.0000,Lower middle income
182,Uzbekistan,UZB,22.500,38.2000,Lower middle income
186,Vietnam,VNM,15.537,43.9000,Lower middle income
187,Vanuatu,VUT,26.739,11.3000,Lower middle income
188,West Bank and Gaza,PSE,30.394,46.6000,Lower middle income
189,Samoa,WSM,26.172,15.3000,Lower middle income
190,"Yemen, Rep.",YEM,32.947,20.0000,Lower middle income
193,Zambia,ZMB,40.471,15.4000,Lower middle income